apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tezos-reward-distributor.fullname" . }}-volume
spec:
 {{- if .Values.storageClassName }}
 storageClassName: {{ .Values.storageClassName }}
 {{- end }}
 accessModes:
    - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
